backend:
  name: git-gateway
  branch: main

media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "posts"
    label: "Posts"
    folder: "publikacje/wpis"
    create: true
    slug: "{{slug}}"
    fields:
  - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Opis", name: "description", widget: "text" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: "Obrazek wyróżniający", name: "thumbnail", widget: "image" }
      - {
          name: "meta_description",
          label: "Meta Description",
          widget: "string",
        }
