backend:
  name: git-gateway
  branch: main
media_folder: "public/dist/images"
public_folder: "/dist/images"
collections:
  - name: "aktualnosci"
    label: "Aktualnosci"
    folder: "src/publikacje/wpis"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Podtytuł", name: "subtitle", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tagi", name: "tags", widget: "list", default: ["post"] }
      - { label: "Zdjecie", name: "image", widget: "image" }
      - { label: "Opis zdjecia", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
